### ISSUE TITLE
e key behaves like w key

### ISSUE THREAD

**Issue by codeRSH** [rcmdnk/vim_ahk#69]
In Vim e key takes us the the "end" of the word. 

However, in in vim_ahk it takes us to the "start" of word, just like 'w' command

Similarly no difference noted between 'w' & 'W' , 'b' & 'B' etc. ? 

Can these be implemented please?

**Comment by rcmdnk** [comment]
Thank you for the suggestion!

I updated `e` to move to the end of the next word in vim_ahk v0.9.2.
Actually, it is not an exactly `the en of the next word`,
it is `one character left of the next next word`.
Please try it.

Previously, I implemented `e` as same as `w` because there is no exact shortcut to move to the end of the word in Windows.
But it is useless to have same function in both `w` and `e`,
and it may be better to have different function even if it is a rough one.

vim_ahk's `w` uses `Ctrl`+`Right`, which moves the cursor to the beginning of the next word.
And `b` uses `Ctrl`+`Left`, which moves the cursor to the beginning of the previous word.
Now, `e` uses `Ctrl`+`Right`,  `Ctrl`+`Right`, `Left`, which is the end of the next word in most cases, I think.


On the other hand,
in macOS, `Opt`+`Right` moves the cursor to the end of the next word,
and `Opt`+`Left` moves the cursor to the beggining of the previous word.
Then both `w` and `e` actions can be made by using the combinations.
(`w` =  `Opt`+`Right`  `Opt`+`Right` `Opt`+`Left` )

**Comment by rcmdnk** [comment]
Anyway, I don't have an idea to distinguish such `aaa aaa` and `aaa-aaa`, which are distinguished by `w` and `W` in vim.

Therefore, these `w`/`W` , `e/E`, or `w/W` have same functions. (`w`/`W` moves like `w` in Vim.)

**Comment by codeRSH** [comment]
Hi, Thanks for the reply and update. 

Actually the implementation of `e` is still not perfect. You have implemented it to be the end of "next word" . But it should be end of "current word". Moreover, through `e` you are moving the cursor to the "space" between the words. It should move the cursor the "Left of space" (which should usually be end of the current word). 

So, instead of `e` uses `Ctrl`+`Right`, `Ctrl`+`Right`, `Left`
I think you should implement : `e` uses `Ctrl`+`Right`, `Left`, `Left`

**Comment by rcmdnk** [comment]
It is a kind of limitation that vim_ahk can not know where the cursor is (if it is in the word or edge of the word).

If it uses `Ctrl`+`Right`, `Left`, then the cursor go to the end of current word.
But it sticks there even if you push more than 2 times.

On the other hand,  `Ctrl`+`Right`,  `Ctrl`+`Right`, `Left` moves the cursor to the end of the next word directly.
But it can go to the next end of the word if you push `e` again.

In the former case, we need to move by `w` and use `e` when we needs. `e` is not a move command any more.
In the latter case, although the first step is a bit tricky, you can go the end of current word by `b` `b` `e`, or `w` `h`.

For now, I feel better to keep `e` as moving command as the latter case.

**Comment by codeRSH** [comment]
OK I understand. The current implementation is not perfect but at least it
works .

Thanks for your efforts .

**Comment by codeRSH** [comment]
Closing the issue as I think nothing else can be done about `e` . Thank for making the `e` functionality work though.
